const products = [
    //nhạc
    {
        id : 1,
        link : "https://www.youtube.com/embed/I2NKVzaI6Bs",
        name :  "Vì Món Quà Chính Là Trên Nụ Cười Em Thôi... Bắt Cóc Con Tim (Orinn Remix) - Lou Hoàng | Remix Tiktok",
        clan : "Orinn Remix",
        like : '"98&nbsp;N lượt xem" * 7 ngày trước',
    },
    {
        id : 2,
        link : "https://www.youtube.com/embed/uMacmXLsmNg",
        name :  "Cách Ngạn - Diêu Lục Nhất || 隔岸 - 姚六一",
        clan : "Hạc Hiên(鹤轩)",
        like : '"2&nbsp;Tr lượt xem" * 2 năm trước',
    },
    {
        id : 3,
        link : "https://www.youtube.com/embed/Xlvr4A4hmhM",
        name :  "Pháo Hồng (H2O Remix) - Đạt Long Vinh | Nụ Cười Ai Nát Lòng Ngày Mai Em Lấy Chồng Hot TikTok",
        clan : "H2O Remix",
        like : '"11&nbsp;Tr lượt xem" * 1 tháng trước',
    },
    {
        id : 4,
        link : "https://www.youtube.com/embed/_wJh2CrolH0",
        name :  "Baby Can You Kiss Me, Ở Sâu Trong Tâm Trí...Lạc Vào Trong Mơ - Simon C ft. Wuy 「Jena Remix",
        clan : "Jena Music",
        like : '"2.7&nbsp;Tr lượt xem" * 2 tháng trước',
    },
    {
        id : 5,
        link : "https://www.youtube.com/embed/b0UpZkMqn0Y",
        name :  "[ Mashup ] Anh Không Làm Gì Đâu Anh Thề × Sunburst - 惰人说梦 (DJ版) | 抖音神曲",
        clan : "Kewnit Music",
        like : '"218&nbsp;N lượt xem" * 1 năm trước',
    },
    {
        id : 6,
        link : "https://www.youtube.com/embed/y576-ONm5II",
        name :  "Lyrics || YÊU 5 - Rhymastic",
        clan : "Jen Hoang",
        like : '"109&nbsp;Tr lượt xem" * 5 năm trước',
    },
    {
        id : 7,
        link : "https://www.youtube.com/embed/_AL4IwHuHlY",
        name :  "#Phao #2PhutHon #Kaiz",
        clan : "Distraction",
        like : '"126&nbsp;Tr lượt xem" * 1 năm trước',
    },
    {
        id : 8,
        link : "https://www.youtube.com/embed/99vsVY-A2zE",
        name :  "DÂN CHƠI XÓM - Rap Việt - MCK x justatee - giọng ca vàng trong xóm đi vào, dạt sang 1 bên hết đi nào",
        clan : "Long Music",
        like : '"4.1&nbsp;Tr lượt xem" * 1 năm trước',
    },
    {
        id : 9,
        link : "https://www.youtube.com/embed/uO1dO0CMkIU",
        name :  "Em Là Bad Girl Trong Bộ Váy Ngắn (Short Skirt) - VP NIZ X Trần Huyền Diệp (Prod. CM1X)",
        clan : "NIZ Official",
        like : '"23&nbsp;Tr lượt xem" * 1 năm trước',
    },
    {
        id : 10,
        link : "https://www.youtube.com/embed/jgZkrA8E5do",
        name :  'TOULIVER x BINZ - "BIGCITYBOI" (Official Music Video)',
        clan : "Binz Da Poet",
        like : '"93&nbsp;Tr lượt xem" * 2 năm trước',
    },
    {
        id : 11,
        link : "https://www.youtube.com/embed/3q1VXsfxPWk",
        name :  "Quá Khứ Kia Của Anh Chỉ Còn Lại Những Giá Băng Remix ( Slowed) Nhạc Remix Hot TikTok 2022",
        clan : "Box Chill",
        like : '"102&nbsp;N lượt xem" * 1 tháng trước',
    },
    {
        id : 12,
        link : "https://www.youtube.com/embed/5_Y-pOScwww",
        name :  "Bên Trên Tầng Lầu Remix|(Tăng Duy Tân)||Nhạc Nền Hot Tik Tok Cực Gây Nghiện",
        clan : "Seju Remixヅ",
        like : '"41&nbsp;N lượt xem" * 3 tuần trước',
    },
    {
        id : 13,
        link : "https://www.youtube.com/embed/fxk1ZT3NC3s",
        name :  "YÊU MỘT NGƯỜI CÓ LẼ REMIX - HIẾU DẠ HOA FT THÁI HOÀNG | Ver Remix Hot Tiktok 2022",
        clan : "nganledm",
        like : '"157&nbsp;N lượt xem" * 5 tháng trước',
    },
    {
        id : 14,
        link : "https://www.youtube.com/embed/a9VDyw-5Ur0",
        name :  "Phố Đã Lên Đèn (Lofi) - Huyền Tâm Môn | Lyrics Video",
        clan : "Nhạc Lofi Chill",
        like : '"6&nbsp;Tr lượt xem" * 1 năm trước',
    },
    {
        id : 15,
        link : "https://www.youtube.com/embed/JgggA8Jtzyg",
        name :  "BÔNG HOA CHẲNG THUỘC VỀ TA - NHƯ VIỆT | OFFICIAL LYRICS VIDEO",
        clan : "Như Việt",
        like : '"51&nbsp;Tr lượt xem" * 3 năm trước',
    },
    {
        id : 16,
        link : "https://www.youtube.com/embed/KCXOWNl2iCM",
        name :  "Dù Cho Mai Về Sau (Lofi Ver.) - buitruonglinh x Freak D",
        clan : "Freak D Music",
        like : '"20&nbsp;Tr lượt xem" * 1 năm trước',
    },
]
